name: Deploy to Staging

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="env=staging" \
            -var="image_name=${{ secrets.ACR_LOGIN_SERVER }}/awesome-devops-app:${{ github.sha }}" \
            -var="acr_login_server=${{ secrets.ACR_LOGIN_SERVER }}" \
            -var="acr_username=${{ secrets.ACR_USERNAME }}" \
            -var="acr_password=${{ secrets.ACR_PASSWORD }}"


      - name: Run Smoke Test
        run: curl -f https://${{ secrets.STAGING_APP_URL }} || exit 1

      - name: Terraform Destroy (Teardown)
        run: |
          cd terraform
          terraform destroy -auto-approve -var="env=staging"
